### ISSUE TITLE
Bio Alexy

### ISSUE THREAD

**Issue by Zer0xxxx** [InVR-Intech-Paris/InVR-blog#3]
Il faut qu'Alexy réalise la petite bio de lui.

Dans ce petit fichier.
https://github.com/InVR-InTech-Paris/InVR-blog/blob/main/content/authors/alexy/_index.md

**Comment by alexyvanot** [comment]
@Zer0xxxx Il faudrait d'abord que  tu fasse ta bio à toi comme ça tu nous guide pour la présentation de la bio... bonne nuitée :P

**Comment by Zer0xxxx** [comment]
Projet d'études de cuck. Je close l'issue.
Je reprends le code pour moi et bosser de moi-même sur MES projets.
